user r10user
topic readwrite sensors/adw220/dev01/raw

user MSIuser 
topic read sensors/adw220/+/raw

user MSIuser 
topic read sensors/adw220/dev01/pred/#

user adw_bridge_user
topic write sensors/adw220/dev01/raw

user adw_collector_user
topic read sensors/adw220/+/raw

user infer_collector_user
topic read sensors/adw220/+/raw

user infer_collector_user
topic write sensors/adw220/dev01/pred/#