listener 1883
protocol mqtt

# === Listener WebSockets para el HTML ===
listener 9001
protocol websockets

allow_anonymous false
password_file C:\Users\juand\OneDrive\Documents\Uni\2025-2\Gamaco\RED\Medicion\mosquitto_data\passwd.txt

persistence true
persistence_location C:\Users\juand\OneDrive\Documents\Uni\2025-2\Gamaco\RED\Medicion\mosquitto_data\persist\

acl_file C:\Users\juand\OneDrive\Documents\Uni\2025-2\Gamaco\RED\Medicion\mosquitto_data\acls.conf

log_type all